# Generated by Django 5.1.3 on 2024-11-23 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id_fabricante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_fabricante', models.CharField(max_length=150)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('sitio_web', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('sitio_web', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaracteristicaEquipo',
            fields=[
                ('id_caracteristica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_caracteristica', models.CharField(max_length=150)),
                ('valor_caracteristica', models.CharField(blank=True, max_length=255, null=True)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imss_app.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField()),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imss_app.departamento')),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imss_app.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='AplicacionEquipo',
            fields=[
                ('id_aplicacion', models.AutoField(primary_key=True, serialize=False)),
                ('aplicacion', models.CharField(max_length=255)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imss_app.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEquipo',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_evento', models.DateField()),
                ('tipo_evento', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imss_app.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_mantenimiento', models.DateField()),
                ('tipo_mantenimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imss_app.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('termino_busqueda', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imss_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imss_app.equipo')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imss_app.proveedor')),
            ],
            options={
                'unique_together': {('id_equipo', 'id_proveedor')},
            },
        ),
    ]
